---
azs:
- name: z1
  cpi: aws
  cloud_properties: {availability_zone: ((terraform_outputs_zone0)) }
- name: z2
  cpi: aws
  cloud_properties: {availability_zone: ((terraform_outputs_zone1)) }
- name: z3
  cpi: aws
  cloud_properties: {availability_zone: ((terraform_outputs_zone2)) }

disk_types:
- name: 5GB
  disk_size: 5120
  cloud_properties:
    type: gp2
- name: 10GB
  disk_size: 10240
  cloud_properties:
    type: gp2
- name: 100GB
  disk_size: 102400
  cloud_properties:
    type: gp2
- name: 200GB
  disk_size: 204800
  cloud_properties:
    type: gp2
- name: 500GB
  disk_size: 512000
  cloud_properties:
    type: gp2

networks:
  - name: cf
    type: dynamic
    subnets:
      - az: z1
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_cf1_subnet_id))

      - az: z2
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_cf2_subnet_id))

      - az: z3
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_cf3_subnet_id))

  - name: cell
    type: dynamic
    subnets:
      - az: z1
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_cell1_subnet_id))

      - az: z2
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_cell2_subnet_id))

      - az: z3
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_cell3_subnet_id))

  - name: router
    type: dynamic
    subnets:
      - az: z1
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_router1_subnet_id))

      - az: z2
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_router2_subnet_id))

      - az: z3
        dns: [10.0.0.2]
        cloud_properties:
          subnet: ((terraform_outputs_router3_subnet_id))

vm_types:
- name: nano
  cloud_properties:
    instance_type: ((nano_vm_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: small
  cloud_properties:
    instance_type: ((small_vm_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: errand
  cloud_properties:
    instance_type: ((small_vm_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2
    iam_instance_profile: bosh-errand

- name: medium
  cloud_properties:
    instance_type: ((medium_vm_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: large
  cloud_properties:
    instance_type: ((large_vm_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: xlarge
  cloud_properties:
    instance_type: ((xlarge_vm_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: router
  cloud_properties:
    instance_type: ((router_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: slim_router
  cloud_properties:
    instance_type: ((slim_router_instance_type))
    ephemeral_disk:
      size: 10240
      type: gp2

- name: cell
  cloud_properties:
    instance_type: ((cell_instance_type))
    ephemeral_disk:
      size: 204800
      type: gp2
    security_groups:
    - ((terraform_outputs_rds_broker_db_clients_security_group))
    - ((terraform_outputs_elasticache_broker_clients_security_group))
    - ((terraform_outputs_default_security_group))

- name: small_cell
  cloud_properties:
    instance_type: ((small_cell_instance_type))
    ephemeral_disk:
      size: 102400
      type: gp2
    security_groups:
    - ((terraform_outputs_rds_broker_db_clients_security_group))
    - ((terraform_outputs_elasticache_broker_clients_security_group))
    - ((terraform_outputs_default_security_group))

vm_extensions:
- name: 64g_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 65536
      type: gp2

- name: cf_cc_instance_profile
  cloud_properties:
    iam_instance_profile: cf-cloudcontroller

- name: cf_rds_client_sg
  cloud_properties:
    security_groups:
    - ((terraform_outputs_default_security_group))
    - ((terraform_outputs_cf_rds_client_security_group))

# This has to duplicate the cf_rds_client_security_group because
# vm_extensions are only shallow merged, and you therefore can't use more
# than one that specifies security groups.
# https://github.com/cloudfoundry/bosh/issues/1177
- name: cf_cc_security_groups
  cloud_properties:
    security_groups:
    - ((terraform_outputs_default_security_group))
    - ((terraform_outputs_cf_rds_client_security_group))
    - ((terraform_outputs_cloud_controller_security_group))

- name: cf_loggregator_doppler_target_groups
  cloud_properties:
    lb_target_groups:
      - ((terraform_outputs_cf_loggregator_rlp_target_group_name))
      - ((terraform_outputs_cf_doppler_target_group_name))

- name: ssh_proxy_elb
  cloud_properties:
    elbs:
    - ((terraform_outputs_cf_ssh_proxy_elb_name))

- name: cf_router_target_groups
  cloud_properties:
    lb_target_groups:
    - ((terraform_outputs_cf_router_app_domain_https_target_group_name))
    - ((terraform_outputs_cf_router_system_domain_https_target_group_name))
