---
# Make everything really small
#
# large  => medium
# medium => small
# small  => nano

- type: replace
  path: /instance_groups/name=api/vm_type
  value: medium

- type: replace
  path: /instance_groups/name=cc-worker/vm_type
  value: small

- type: replace
  path: /instance_groups/name=diego-api/vm_type
  value: small

- type: replace
  path: /instance_groups/name=doppler/vm_type
  value: medium

- type: replace
  path: /instance_groups/name=log-api/vm_type
  value: medium

- type: replace
  path: /instance_groups/name=nats/vm_type
  value: small

- type: replace
  path: /instance_groups/name=scheduler/vm_type
  value: small

- type: replace
  path: /instance_groups/name=uaa/vm_type
  value: small

- type: replace
  path: /instance_groups/name=router/vm_type
  value: slim_router

- type: replace
  path: /instance_groups/name=prometheus/vm_type
  value: small

- type: replace
  path: /instance_groups/name=prometheus/persistent_disk_type
  value: 100GB

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/storage/tsdb/retention/size
  value: 90GB
