---
- type: remove
  path: /instance_groups/name=diego-cell/vm_extensions

- type: replace
  path: /instance_groups/name=diego-cell/azs/-
  value: z3

- type: replace
  path: /instance_groups/name=diego-cell/instances
  value: ((cell_instances))

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/proxy/additional_memory_allocation_mb?
  value: 48

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs3-rootfs-setup/properties/cflinuxfs3-rootfs/trusted_certs
  value:
    - ((aws_rds_combined_ca_bundle))
    - ((diego_instance_identity_ca.ca))
    - ((uaa_ssl.ca))

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/trusted_ca_certificates
  value:
    - ((diego_instance_identity_ca.ca))
    - ((uaa_ssl.ca))

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden?/log_level
  value: error

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/debug_listen_address

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/destroy_containers_on_start

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego?/executor/memory_capacity_mb
  value: ((cell_memory_capacity_mb))

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/tcp

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/uaa

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/diego/route_emitter/sync_interval_in_seconds?
  value: 30

- type: replace
  path: /instance_groups/name=diego-cell/networks/0/name
  value: cell

- type: replace
  # Our VMs have an MTU set of 9001 on eth0
  #
  # Silk will automatically detect the MTU size and remove 50 bytes from it
  # to account for the vxlan packet overhead, this does not account for IPsec
  #
  # There will be at least 73 bytes of overhead due to IPsec
  path: /instance_groups/name=diego-cell/jobs/name=silk-cni/properties/mtu?
  value: 8900

# Override the vpa bosh link, so that we can add isolation segments
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=vxlan-policy-agent/provides?/vpa?
  value:
    as: vpa-default
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=silk-cni/consumes?/vpa?
  value:
    from: vpa-default
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=silk-daemon/consumes?/vpa?
  value:
    from: vpa-default
