---

- type: replace
  path: /releases/-
  value:
    name: elasticache-broker
    version: 0.1.8
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/elasticache-broker-0.1.8.tgz
    sha1: a1b83e8f8972b71756bc622442590f34ff72a551

- type: replace
  path: /addons/name=loggregator_agent/exclude/jobs/-
  value:
    name: elasticache-broker
    release: elasticache-broker

- type: replace
  path: /instance_groups/-
  value:
    name: elasticache_broker
    azs: [z1, z2]
    instances: 2
    vm_type: nano
    vm_extensions:
      - elasticache_broker
    stemcell: default
    networks:
      - name: cf
    jobs:
      - name: elasticache-broker
        release: elasticache-broker
        properties:
          elasticache-broker:
            broker_name: "elasticache-broker"
            broker_username: "elasticache-broker"
            broker_password: ((secrets_elasticache_broker_admin_password))
            kms_key_id: alias/elasticache-broker
            secrets_manager_path: elasticache-broker/((environment))
            region: "((terraform_outputs_region))"
            cache_subnet_group_name: ((terraform_outputs_elasticache_broker_subnet_group_name))
            vpc_security_group_ids:
            - ((terraform_outputs_elasticache_broker_instances_security_group_id))

            catalog:
              services:
                - id: 7b94ab02-478f-4c1b-95d8-21522672930b
                  name: redis
                  description: AWS ElastiCache Redis service
                  metadata:
                    displayName: Redis
                    longDescription: |
                      Redis is an in-memory data structure project implementing a distributed, in-memory key-value 
                      database with optional durability. Redis supports different kinds of abstract data structures,
                      such as strings, lists, maps, sets, sorted sets, HyperLogLogs, bitmaps, streams, and spatial
                      indexes.
                    providerDisplayName: Amazon Web Services
                    documentationUrl: https://docs.cloud.service.gov.uk/deploying_services/redis/
                    supportUrl: https://www.cloud.service.gov.uk/support
                    AdditionalMetadata:
                      otherDocumentation:
                        - https://redis.io/documentation
                        - https://docs.aws.amazon.com/elasticache
                      usecase:
                        - Cache
                        - Session management
                        - Queues
                  tags:
                    - elasticache
                    - redis
                  bindable: true
                  plan_updateable: true
                  plans:
                    - id: 3a51701c-eef3-447c-882b-907ad2bcb7ab
                      name: tiny-clustered-3.2
                      active: false
                      description: DEPRECATED - do not use, 568MB RAM, clustered (1 shard), single node, no failover, daily backups
                      free: true
                      metadata:
                        displayName: Tiny Clustered
                    - id: c84d1bef-9500-4ce9-88b2-c0bd421bbf8a
                      name: tiny-3.2
                      description: 568MB RAM, single node, no failover, daily backups (for instances created after 21/1/2019)
                      free: true
                      metadata:
                        displayName: Tiny
                        AdditionalMetadata:
                          backups: true
                          encrypted: true
                          highlyAvailable: false
                          memory:
                            amount: 568
                            unit: MB
                          version: 3.2
                    - id: b6949ea7-5c98-4c69-b981-4b5318ea8b7c
                      name: medium-ha-3.2
                      description: 6.37GB RAM, highly-available, daily backups
                      free: false
                      metadata:
                        displayName: Medium highly-available
                        AdditionalMetadata:
                          backups: true
                          encrypted: true
                          highlyAvailable: true
                          memory:
                            amount: 6.37
                            unit: GB
                          version: 3.2
                    - id: ea5c8cc3-74e6-4b15-bd61-bbe244cfe63d
                      name: tiny-ha-3.2
                      description: 1.5GB RAM, highly-available, daily backups
                      free: false
                      metadata:
                        displayName: Tiny highly-available
                        AdditionalMetadata:
                          backups: true
                          encrypted: true
                          highlyAvailable: true
                          memory:
                            amount: 1.5
                            unit: GB
                          version: 3.2
                    - id: 9162ed5b-0c88-4f43-bcaf-c6d4a45dd243
                      name: small-ha-3.2
                      description: 3GB RAM, highly-available, daily backups
                      free: false
                      metadata:
                        displayName: Small highly-available
                        AdditionalMetadata:
                          backups: true
                          encrypted: true
                          highlyAvailable: true
                          memory:
                            amount: 3
                            unit: GB
                          version: 3.2

            plan_configs:
              3a51701c-eef3-447c-882b-907ad2bcb7ab:
                instance_type: cache.t2.micro
                replicas_per_node_group: 0
                shard_count: 1
                snapshot_retention_limit: 7
                automatic_failover_enabled: true
                parameters:
                  cluster-enabled: 'yes'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'
              c84d1bef-9500-4ce9-88b2-c0bd421bbf8a:
                instance_type: cache.t2.micro
                replicas_per_node_group: 0
                shard_count: 1
                snapshot_retention_limit: 7
                automatic_failover_enabled: false
                parameters:
                  cluster-enabled: 'no'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'
              b6949ea7-5c98-4c69-b981-4b5318ea8b7c:
                instance_type: cache.m5.large
                replicas_per_node_group: 1
                shard_count: 1
                snapshot_retention_limit: 7
                automatic_failover_enabled: true
                parameters:
                  cluster-enabled: 'no'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'
              ea5c8cc3-74e6-4b15-bd61-bbe244cfe63d:
                instance_type: cache.t2.small
                replicas_per_node_group: 1
                shard_count: 1
                snapshot_retention_limit: 7
                automatic_failover_enabled: true
                parameters:
                  cluster-enabled: 'no'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'
              9162ed5b-0c88-4f43-bcaf-c6d4a45dd243:
                instance_type: cache.t2.medium
                replicas_per_node_group: 1
                shard_count: 1
                snapshot_retention_limit: 7
                automatic_failover_enabled: true
                parameters:
                  cluster-enabled: 'no'
                  maxmemory-policy: volatile-lru
                  reserved-memory: '0'


- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: elasticache_broker_instances
    rules:
      - protocol: tcp
        destination: ((terraform_outputs_aws_backing_service_cidr_all))
        ports: '6379'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_running_security_groups/-
  value: elasticache_broker_instances

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: elasticache_broker_instances

- type: replace
  path: /variables/-
  value:
    name: secrets_elasticache_broker_admin_password
    type: password
